# Generated by Django 5.0.6 on 2024-05-29 09:56

import jsonfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('img_blocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='colors',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
