# Generated by Django 5.0.6 on 2024-05-30 11:43

import jsonfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('img_blocks', '0003_alter_imagemodel_colors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='colors',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
