# Generated by Django 5.0.6 on 2024-05-30 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('img_blocks', '0004_alter_imagemodel_colors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='colors',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
