# Generated by Django 5.0.6 on 2024-06-14 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('img_blocks', '0005_alter_imagemodel_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='img_blocks.imagemodel'),
        ),
    ]
