# Generated by Django 5.0.6 on 2024-06-17 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('img_blocks', '0006_imagemodel_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='main_colors',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
